nombre1 = input("Ingresa un nombre: ")
nombre2 = input("Ingresa otro nombre: ")
verbo = input("Ingresa un verbo: ")
verbo2 = input("Ingresa un segundo verbo: ")
verbo3 = input("Ingresa un tercer verbo: ")
verbo4 = input("Ingresa un cuarto verbo: ")
verbo5  = input("Ingresa un quinto verbo: ")
animal = input("Ingresa el nombre de un animal: ")
sustantivo = input("Ingresa un sustantivo: ")
sustantivo2 = input("Ingresa un segundo sustantivo: ")
comida1 = input("Ingresa una comida: ")
comida2 = input("Ingresa una segunda comida: ")
fruta = input("Ingresa una fruta: ")
adjetivofp = input("Ingresa un adjetivo femenino plural: ")
cuerpo_de_agua = input("Ingresa un cuerpo de agua: ")
adjetivosm = input("Ingresa un adjetivo masculino singular: ")

print("Un día, {} y {} decidieron {} durante las vacaciones de verano, {} recogió un(a) {} y se fueron.".format(nombre1, nombre2, verbo, nombre1, sustantivo))
print("{} pensó que debieron {}, que {} creyó muy loco. '¡Son las vacaciones!' Tenemos que {}!-exclamó {}.".format(nombre2, verbo2, nombre1,verbo3,nombre1))
print("Mientras viajaban, {} vio un(a) {} escalando un(a) {}, y eso le dio miedo a {}".format(nombre1, animal, sustantivo,nombre2))
print("Luego fue la hora de la merienda, así {} sugirió que comieran {} y {} y bebieran jugo de {}".format(nombre2, comida1,comida2,fruta))
print("Verano es tiempo de para tener experiencias {}, por eso {} y {} querían hacer de todo".format(adjetivofp,nombre1,nombre2))
print("Después de {} rapidamente en el/la {}, fue hora de {}.".format(verbo4,cuerpo_de_agua,verbo5))
print("¡Había sido otro día muy {} del verano!".format(adjetivosm))